background_opacity	0.6

font_family		Cascadia Code NF
font_size		12

window_margin_width	15
enable_audio_bell	false


# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME
#
repaint_delay		50
