[plugin]
prepend_preloaders = [
  { mime = "audio/*", run = "mediainfo" },
  { mime = "video/*", run = "mediainfo --no-preview" },
  { mime = "image/*", run = "mediainfo --no-metadata" },
  { mime = "application/subrip", run = "mediainfo" },
  { url = "*.{ai,eps,ait}", run = "mediainfo" },
  { mime = "application/postscript", run = "mediainfo" },
  { mime = "application/dvb.ait", run = "mediainfo" },
  { mime = "application/vnd.adobe.illustrator", run = "mediainfo" },
  { url = '*.typ', run = 'preview-typst' },
]