#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
export EDITOR=nvim
export HISTSIZE=-1
export HISTFILESIZE=-1
export OLLAMA_NUM_PARALLEL=4

fastfetch

alias cva='python -m venv .venv'
alias va='source .venv/bin/activate'
alias dva='deactivate'

# alias ls='ls --color=auto'
alias ls='eza --color=always'
alias grep='grep --color=always'
alias less='less -R'

alias mati='systemctl poweroff'
alias restart='systemctl reboot'
alias tidur='systemctl hibernate'

alias cdhy='cd ~/.config/hypr'
alias cdnr='cd ~/.config/niri/'
alias cdwb='cd ~/.config/waybar'
alias cdnv='cd ~/.config/nvim'
alias cdqu='cd ~/.config/quickshell'
alias cdwd='cd ~/ThePreservedLexicon/CS/TheDigitalForge/WebDev/'
alias cdui='cd ~/ThePreservedLexicon/CS/CSUI/'
alias cdgs='cd ~/.config/ags/'
alias cddf='cd ~/ThePreservedLexicon/CS/TheDigitalForge/'
alias cdcf='cd ~/.config/'

alias warpc='warp-cli connect && exit'
alias warpdc='warp-cli disconnect && exit'
alias warpr='warp-cli disconnect && warp-cli connect && exit'
alias warps='warp-cli status'
alias rqu='pkill qs && qs & disown'
alias rhp='pkill hyprpaper && hyprpaper & disown'
alias rwb='pkill waybar && waybar & disown'
alias nmres='sudo systemctl --now restart NetworkManager'

alias nbash='nvim ~/.bashrc'
alias sbash='source ~/.bashrc'

alias s='yay -Ss --color=always'
alias i='yay --needed --noconfirm -S --color=always'
alias ui='yay -Rns --color=always'
alias updatealias='sudo flatpak update --color=always && yay --needed --noconfirm --color=always -Syu'
alias apdet='updatealias && exit'
alias apdetsh='updatealias && mati'

alias anime='ani-cli'
alias ff='fastfetch'

alias yt='yt-dlp -S "res:480,vcodec:h264" \
  --merge-output-format mp4 \
  --postprocessor-args "ffmpeg:-c:v libx264 -crf 28 -preset slow -profile:v main -pix_fmt yuv420p -c:a aac -b:a 96k -movflags +faststart" '
alias ig='yt-dlp --cookies-from-browser firefox \
  --merge-output-format mp4 \
  --postprocessor-args "ffmpeg:-vf scale=-2:480 -c:v libx265 -crf 28 -preset slow -profile:v main -pix_fmt yuv420p -c:a aac -b:a 96k -movflags +faststart" '
alias tt='yt-dlp \
  -S "res:480,vcodec:h265" \
  --merge-output-format mp4 \
  --postprocessor-args "ffmpeg:-vf scale=-2:480 -c:v libx265 -crf 28 -preset slow -profile:v main -pix_fmt yuv420p -c:a aac -b:a 96k -movflags +faststart" '

alias dorong='git push -u origin main'
alias gitaccCB='git config --local user.name "CatBoi1107" && git config --local user.email "therealjohnsmith1256@gmail.com"'
alias gitaccUI='git config --local user.name "AhmadCSUI" && git config --local user.email "ahmad.shanahan@ui.ac.id"'
alias gitaccASZ='git config --local user.name "aszorya" && git config --local user.email "ahmadszorya@gmail.com"'
alias komit='git add . && git commit -m'

alias junit='java -cp .:/usr/share/java/junit.jar org.junit.runner.JUnitCore'
# PS1='[\u@\h \W]\$ '
PS1='< \W > '
alias synckb='scrcpy -e --no-video --no-audio --keyboard=uhid'

alias nvint='sudo envycontrol -s integrated'
alias nvhyb='sudo envycontrol -s hybrid'
alias nvgpu='sudo envycontrol -s nvidia'

# https://en.wikipedia.org/wiki/ANSI_escape_code
# PS1="\e[38;5;61m\W \e[38;5;71m\$ \[\e[0m\]"
# pnpm
export PNPM_HOME="/home/h/.local/share/pnpm"
export CLASSPATH=".:/usr/share/java/junit.jar"
case ":$PATH:" in
*":$PNPM_HOME:"*) ;;
*) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
eval "$(starship init bash)"
