#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc
# export WLR_DRM_DEVICES="/dev/dri/card1:/dev/dri/card0"
export WAYLAND_DISPLAY=wayland-1

# Superset CLI
export PATH="/home/ahmad/superset/bin:$PATH"

# Added by jcode installer
export PATH="/home/ahmad/.local/bin:$PATH"
