preload = ~/ThePreservedLexicon/Images/CatpuccinNightSky.png
preload = ~/ThePreservedLexicon/Images/GruvCat.png
preload = ~/ThePreservedLexicon/Images/DarkSkyConstellation.png
preload = ~/ThePreservedLexicon/Images/Space-Nebula.png
preload = ~/ThePreservedLexicon/Images/astronaut.jpg
preload = ~/ThePreservedLexicon/Images/AstronautBalloon.jpg

splash = false

wallpaper {
    monitor = eDP-1
    path =  ~/ThePreservedLexicon/Images/AstronautBalloon.jpg
    # splash = false
    # path = ~/ThePreservedLexicon/Images/CatpuccinNightSky.png
    # path = ~/ThePreservedLexicon/Images/GruvCat.png
  }

